preserve_hierarchy: 1
files:
  - source: /YouTubePlayerEX.App.Resources/Localisation/**/*.resx
    translation: /YouTubePlayerEX.App.Resources/Localisation/**/%file_name%.%locale%.%file_extension%
    ignore:
      - /YouTubePlayerEX.App.Resources/Localisation/**/%file_name%.*.%file_extension%
    update_option: update_as_unapproved
    languages_mapping:
      locale:
        es-ES: es
        fr: fr
        it: it
        ja: ja
        ko: ko
        nl: nl
        pt-PT: pt
        ru: ru
        tr: tr
        vi: vi
        zh-CN: zh
        zh-TW: zh-Hant
